### ISSUE TITLE
Documentation doesn't explain how to import the built-in libraries correctly

### ISSUE THREAD

**Issue by Hexcede** [WerWolv/Documentation#11]
The documentation does not explain how to import built-in libraries like `type`. This is not entirely straightforward, as there are several ways to import built-in libraries. E.g. using `#include` or using the `import` keyword. Neither of these are explained or described anywhere in the Pattern Language documentation.

**Comment by C3pa** [comment]
Where's the Pattern Language documentation repository located? I am interested in writing such a section in the docs.
