### ISSUE TITLE
FR: Load/Save patterns in pattern editor

### ISSUE THREAD

**Issue by tlamy** [WerWolv/Documentation#27]
While reengineering a pattern, more than once I edit a pattern and forget to export it after editing. It would be nice to be able to load/save (import/export) it from a small toolbar in the pattern editor itself.

**Comment by paxcut** [comment]
You can right click anywhere in the pattern editor window and select import or export in the context menu unless you are using an old version of ImHex. You can  also load and save projects using shortcuts (Alt-w and Alt-s but i am not sure about the first one)
