### ISSUE TITLE
Pattern Editor missing info on Sections

### ISSUE THREAD

**Issue by yutamago** [WerWolv/Documentation#7]
The documentation on [Sections](https://github.com/WerWolv/Documentation/blob/master/imhex/views/pattern-editor.md#sections) is missing key information on it's usage.

1. `The Pattern Language code can write data into this custom section and place patterns into it.`
**_How?_**
2. Just trying out the function quickly reveals that you're missing an include. This should be mentioned somewhere. Not every reader is familiar with C++ or Rust.
3. This image from the documentation shows `Size` column. How do you define it?
![example from the documentation](https://github.com/WerWolv/Documentation/raw/master/imhex/.gitbook/assets/imhex_cqowB8XMS6.png)
4. How do you define the beginning and the end of a section?

**Comment by paxcut** [comment]
Maybe you overlooked the Pattern Language documentation on [Sections](https://github.com/WerWolv/Documentation/blob/master/pattern_language/core-language/sections.md) which provides answers to some of your questions of not all.
